# Generated by Django 4.0.6 on 2023-05-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(max_length=50, verbose_name='Días')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('nacionalidad', models.CharField(default='Argentina', max_length=12)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('seguro', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Entrenador',
                'verbose_name_plural': 'Entrenadores',
            },
        ),
        migrations.CreateModel(
            name='EntrenamientoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=8)),
                ('cupo_turno', models.IntegerField()),
                ('desde', models.TimeField()),
                ('hasta', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LugarEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=50, verbose_name='Lugar')),
                ('cupo_entrenador', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignarDiasEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.TimeField(blank=True, null=True)),
                ('hasta', models.TimeField(blank=True, null=True)),
                ('dias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenadores.diasentrenamiento', verbose_name='Dias')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenadores.entrenadores', verbose_name='Entrenador')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenadores.lugarentrenamiento', verbose_name='Lugar')),
                ('turno', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='entrenadores.entrenamientoturno')),
            ],
        ),
    ]
