# Generated by Django 4.0.6 on 2023-05-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenamientoturno',
            name='cupo_turno',
        ),
        migrations.RemoveField(
            model_name='entrenamientoturno',
            name='nombre',
        ),
    ]
