# Generated by Django 4.0.6 on 2023-05-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenadores', '0002_remove_entrenamientoturno_cupo_turno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignardiasentrenamiento',
            name='desde',
        ),
        migrations.RemoveField(
            model_name='asignardiasentrenamiento',
            name='hasta',
        ),
    ]
