# Generated by Django 4.0.6 on 2023-03-06 19:07

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bici', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Mujer'), ('M', 'Hombre')], max_length=10, null=True, verbose_name='Sexo')),
                ('edad_desde', models.IntegerField(blank=True, null=True)),
                ('edad_hasta', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoDistancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventoFormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPago', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EventoModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('fechaEvento', models.DateField(help_text='Para competencias')),
                ('temporada', models.CharField(max_length=25)),
                ('nombreEvento', models.CharField(max_length=40)),
                ('lugar', models.CharField(max_length=25)),
                ('cupo', models.IntegerField()),
                ('estado', models.BooleanField(default=True, verbose_name='visible')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('inscribirse', models.BooleanField(default=True)),
                ('publicar', models.BooleanField(default=False)),
                ('seguro', models.BooleanField(default=False)),
                ('bici_disponible', models.ManyToManyField(to='inscripcion.eventobici')),
                ('categoria_disponible', models.ManyToManyField(to='inscripcion.eventocategoria')),
                ('distancia_disponible', models.ManyToManyField(to='inscripcion.eventodistancia')),
                ('modalidad_disponible', models.ManyToManyField(to='inscripcion.eventomodalidade')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fechaEvento'],
            },
        ),
        migrations.CreateModel(
            name='EventoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEquipoPosta', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('formaPago', models.CharField(max_length=40)),
                ('montoDebeAbonar', models.IntegerField()),
                ('montoAbonado', models.IntegerField()),
                ('fechaPago', models.DateField()),
                ('comprobPago', models.ImageField(upload_to='media/pagos')),
                ('comentario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentarios')),
                ('emmac_file', models.ImageField(upload_to='media/eventos/emmac_certif', verbose_name='Foto Emmac o Certifidado Medico ')),
                ('obra_social', models.CharField(max_length=60)),
                ('responsable_tutor', models.CharField(blank=True, help_text='Obligatorio en caso de ser menor de 18 años', max_length=20, null=True)),
                ('relacion_legal', models.CharField(blank=True, choices=[('1', '------'), ('2', 'Madre'), ('3', 'Padre'), ('4', 'Tutor Legal')], default='', max_length=2, null=True)),
                ('dni_responsable', models.IntegerField(blank=True, null=True)),
                ('mail_responsable', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('confirm_pago', models.BooleanField(default=False)),
                ('bici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventobici')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventocategoria')),
                ('distancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventodistancia')),
                ('eventoRelacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventos')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventomodalidade')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['eventoRelacionado'],
            },
        ),
        migrations.AddField(
            model_name='eventos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventotipo', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='EventoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asociado', models.CharField(choices=[('1', 'Asociado'), ('2', 'No Asociado')], default='', max_length=20)),
                ('precio', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventos', verbose_name='Evento')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventoformaspago', verbose_name='Forma')),
            ],
        ),
    ]
