# Generated by Django 4.0.6 on 2023-10-14 00:29

import apps.inscripcion.validators
import ckeditor.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bici', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Bici',
                'verbose_name_plural': 'Bicis',
                'ordering': ['bici'],
            },
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Mujer'), ('M', 'Hombre')], max_length=10, null=True, verbose_name='Sexo')),
                ('edad_desde', models.IntegerField(blank=True, null=True)),
                ('edad_hasta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['categoria'],
            },
        ),
        migrations.CreateModel(
            name='EventoDistancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Distancia',
                'verbose_name_plural': 'Distancias',
                'ordering': ['distancia'],
            },
        ),
        migrations.CreateModel(
            name='EventoFormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPago', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EventoModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'ordering': ['modalidad'],
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('fechaEvento', models.DateField(help_text='Para competencias')),
                ('temporada', models.CharField(max_length=25)),
                ('nombreEvento', models.CharField(max_length=40)),
                ('lugar', models.CharField(max_length=25)),
                ('cupo', models.IntegerField()),
                ('estado', models.BooleanField(default=True, verbose_name='visible')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('inscribirse', models.BooleanField(default=True)),
                ('publicar', models.BooleanField(default=False)),
                ('seguro', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fechaEvento'],
            },
        ),
        migrations.CreateModel(
            name='EventoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.CharField(default='Elegir', max_length=60)),
                ('modalidad', models.CharField(default='Elegir', max_length=60)),
                ('categoria', models.CharField(default='Elegir', max_length=60)),
                ('bici', models.CharField(default='Elegir', max_length=40)),
                ('nombreEquipoPosta', models.CharField(blank=True, default='No', max_length=10, null=True)),
                ('formaPago', models.CharField(max_length=40)),
                ('montoDebeAbonar', models.IntegerField()),
                ('montoAbonado', models.IntegerField(blank=True, default=0, null=True)),
                ('fechaPago', models.DateField(default=datetime.date.today, verbose_name='Fecha de pago:')),
                ('comprobPago', models.FileField(default='media/pagos/sin_costo.jpg', upload_to='media/pagos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.inscripcion.validators.validate_file_size], verbose_name='')),
                ('comentario', models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentarios')),
                ('grupo', models.CharField(blank=True, max_length=30, null=True, verbose_name='Grupo')),
                ('emmac_file', models.ImageField(upload_to='media/eventos/emmac_certif', validators=[apps.inscripcion.validators.validate_file_size], verbose_name='Foto Emmac o Certifidado Medico ')),
                ('obra_social', models.CharField(max_length=60)),
                ('responsable_tutor', models.CharField(blank=True, help_text='Obligatorio en caso de ser menor de 18 años', max_length=20, null=True)),
                ('relacion_legal', models.CharField(blank=True, choices=[('1', '------'), ('2', 'Madre'), ('3', 'Padre'), ('4', 'Otro')], default='', max_length=2, null=True, verbose_name='Tipo Relación')),
                ('relacion', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Defina Relación')),
                ('dni_responsable', models.IntegerField(blank=True, null=True)),
                ('mail_responsable', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_responsable', models.CharField(blank=True, max_length=20, null=True)),
                ('confirm_pago', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('acreditacion', models.BooleanField(default=False, verbose_name='Acreditado')),
                ('numero', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nº corredor')),
                ('eventoRelacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventos')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['eventoRelacionado', '-fechaPago'],
            },
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_corredor', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('tiempo_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('tiempo_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('tiempo_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('tiempo_finished', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('inscripcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.inscripcion', verbose_name='')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-inscripcion'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bici_disponible', models.ManyToManyField(to='inscripcion.eventobici')),
                ('categoria_disponible', models.ManyToManyField(to='inscripcion.eventocategoria')),
                ('distancia_disponible', models.ManyToManyField(to='inscripcion.eventodistancia')),
                ('evento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventos', verbose_name='Evento')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventomodalidade')),
            ],
            options={
                'verbose_name': 'Modalidad Evento',
                'verbose_name_plural': 'Modalidad Eventos',
            },
        ),
        migrations.AddField(
            model_name='eventos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventotipo', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='EventoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asociado', models.CharField(choices=[('1', 'Asociado'), ('2', 'No Asociado')], default='', max_length=20)),
                ('precio', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventos', verbose_name='Evento')),
                ('formaPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventoformaspago', verbose_name='Forma')),
            ],
        ),
    ]
