# Generated by Django 3.2.15 on 2022-10-14 12:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bici', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Mujer'), ('M', 'Hombre')], max_length=10, null=True, verbose_name='Sexo')),
                ('edad_desde', models.IntegerField(blank=True, null=True)),
                ('edad_hasta', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asociado', models.CharField(choices=[('1', 'Asociado'), ('2', 'No Asociado')], default='', max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventoDistancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventoFormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPago', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EventoModalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('fechaEvento', models.DateField(blank=True, help_text='Para competencias', null=True)),
                ('temporada', models.CharField(max_length=25)),
                ('nombreEvento', models.CharField(max_length=40)),
                ('lugar', models.CharField(max_length=25)),
                ('cupo', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fechaEvento'],
            },
        ),
        migrations.CreateModel(
            name='EventoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoEvento', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEquipoPosta', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('formaPago', models.CharField(blank=True, max_length=40, null=True)),
                ('montoDebeAbonar', models.IntegerField(default=0)),
                ('montoAbonado', models.IntegerField()),
                ('fechaPago', models.DateField()),
                ('comprobPago', models.ImageField(upload_to='media/pagos')),
                ('responsable_tutor', models.CharField(blank=True, help_text='Obligatorio en caso de ser menor de 18 años', max_length=20, null=True)),
                ('relacion_legal', models.CharField(choices=[('1', '------'), ('2', 'Madre'), ('3', 'Padre'), ('4', 'Tutor Legal')], default='', max_length=2)),
                ('dni_responsable', models.IntegerField(blank=True, null=True)),
                ('mail_responsable', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_responsable', models.IntegerField(blank=True, null=True)),
                ('confirm_pago', models.BooleanField(default=False)),
                ('bici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventobici')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventocategoria')),
                ('distancia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventodistancia')),
                ('eventoRelacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventos')),
                ('modalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventomodalidade')),
            ],
            options={
                'verbose_name': 'Inscripcion',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['eventoRelacionado'],
            },
        ),
    ]
