# Generated by Django 4.0.6 on 2023-03-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='relacion',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Defina Relación'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='relacion_legal',
            field=models.CharField(blank=True, choices=[('1', '------'), ('2', 'Madre'), ('3', 'Padre'), ('4', 'Tutor Legal')], default='', max_length=2, null=True, verbose_name='Tipo Relación'),
        ),
    ]
