# Generated by Django 3.2.15 on 2022-10-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscripcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventos',
            name='bici_disponible',
            field=models.ManyToManyField(to='inscripcion.EventoBici'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='categoria_disponible',
            field=models.ManyToManyField(to='inscripcion.EventoCategoria'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='distancia_disponible',
            field=models.ManyToManyField(to='inscripcion.EventoDistancia'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='modalidad_disponible',
            field=models.ManyToManyField(to='inscripcion.EventoModalidade'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventotipo', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='eventocosto',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventos', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='eventocosto',
            name='formaPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripcion.eventoformaspago', verbose_name='Forma'),
        ),
    ]
