# Generated by Django 4.0.6 on 2023-03-08 14:08

import apps.inscripcion.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_inscripcion_relacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='comprobPago',
            field=models.ImageField(upload_to='media/pagos', validators=[apps.inscripcion.validator.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='emmac_file',
            field=models.ImageField(upload_to='media/eventos/emmac_certif', validators=[apps.inscripcion.validator.validate_file_size], verbose_name='Foto Emmac o Certifidado Medico '),
        ),
    ]
