# Generated by Django 3.2.15 on 2022-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='emmac_file',
            field=models.ImageField(blank=True, null=True, upload_to='media/eventos/emmac_certif', verbose_name='Foto Emmac o Certifidado Medico '),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='obra_social',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='cupo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fechaEvento',
            field=models.DateField(help_text='Para competencias'),
        ),
    ]
