# Generated by Django 4.0.6 on 2023-03-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_alter_inscripcion_comprobpago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='relacion_legal',
            field=models.CharField(blank=True, choices=[('1', '------'), ('2', 'Madre'), ('3', 'Padre'), ('4', 'Otro')], default='', max_length=2, null=True, verbose_name='Tipo Relación'),
        ),
    ]
