# Generated by Django 3.2.15 on 2022-10-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0003_auto_20221018_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='emmac_file',
            field=models.ImageField(default='emmac', upload_to='media/eventos/emmac_certif', verbose_name='Foto Emmac o Certifidado Medico '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='formaPago',
            field=models.CharField(default='-', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='montoDebeAbonar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='relacion_legal',
            field=models.CharField(blank=True, choices=[('1', '------'), ('2', 'Madre'), ('3', 'Padre'), ('4', 'Tutor Legal')], default='', max_length=2, null=True),
        ),
    ]
