# Generated by Django 3.2.15 on 2022-10-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_auto_20221025_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventos',
            name='seguro',
            field=models.BooleanField(default=False),
        ),
    ]
