# Generated by Django 3.2.15 on 2022-10-14 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('fecha_emision_emmac', models.DateField(default=datetime.date.today, verbose_name='Fecha emisión Emmac')),
                ('emmac_file', models.ImageField(blank=True, null=True, upload_to='media/emmac', verbose_name='Foto Emmac ')),
                ('obra_social', models.CharField(blank=True, max_length=20, null=True)),
                ('con_entrenador', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], default=2, max_length=2, verbose_name='Entrenador? si/no')),
                ('responsable_tutor', models.CharField(blank=True, default='', help_text='campos obligatorios en caso de ser menor de 18 años', max_length=20, null=True)),
                ('relacion_legal', models.CharField(choices=[('1', '------'), ('2', 'Madre'), ('3', 'Padre'), ('4', 'Tutor Legal')], default='', help_text='campo obligatorios en caso de ser menor de 18 años', max_length=2)),
                ('dni_responsable', models.IntegerField(blank=True, help_text='campo obligatorios en caso de ser menor de 18 años', null=True)),
                ('mail_responsable', models.EmailField(blank=True, help_text='campo obligatorios en caso de ser menor de 18 años', max_length=254, null=True)),
                ('telefono_responsable', models.IntegerField(blank=True, help_text='campo obligatorios en caso de ser menor de 18 años', null=True)),
                ('estado', models.BooleanField(default=False)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsociadoCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AsociadoFormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPago', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AsociadoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAsociado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EntrenamientoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=8)),
                ('cupo_turno', models.IntegerField()),
                ('desde', models.TimeField()),
                ('hasta', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EntrenadoresKempe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('cupo_entrenador', models.IntegerField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.entrenamientoturno')),
            ],
        ),
        migrations.CreateModel(
            name='AsociadoPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAsociadoPago', models.CharField(blank=True, max_length=40, null=True, verbose_name='Forma de pago elegida:')),
                ('formaPago', models.CharField(blank=True, max_length=40, null=True, verbose_name='Forma de pago elegida:')),
                ('montoDebeAbonar', models.IntegerField(blank=True, null=True, verbose_name='Monto que corresponde abonar:')),
                ('montoAbonado', models.IntegerField(null=True)),
                ('fechaPago', models.DateField(verbose_name='Fecha de pago del comprobante')),
                ('comprobPago', models.ImageField(default='comprobante de Pago', null=True, upload_to='media/pagos', verbose_name='Adjuntar compropante de pago')),
                ('confirm_pago', models.BooleanField(default=False)),
                ('opcionElegida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.asociadocosto', verbose_name='Seleccione su opción de pago::')),
            ],
            options={
                'ordering': ['fechaPago'],
            },
        ),
    ]
