# Generated by Django 3.2.15 on 2022-10-14 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociadopagos',
            name='personaAsociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='PersonaAsociada'),
        ),
        migrations.AddField(
            model_name='asociadocosto',
            name='formaPago',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.asociadoformaspago'),
        ),
        migrations.AddField(
            model_name='asociadocosto',
            name='tipoSocio',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.asociadotipo'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='entrenador',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='socio.entrenadoreskempe'),
        ),
        migrations.AddField(
            model_name='asociado',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asociado',
            name='tipoAsociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.asociadotipo', verbose_name='Tipo de Asociado'),
        ),
    ]
