# Generated by Django 3.2.15 on 2022-10-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='telefono_responsable',
            field=models.CharField(blank=True, help_text='campo obligatorios en caso de ser menor de 18 años', max_length=30, null=True),
        ),
    ]
