# Generated by Django 3.2.15 on 2022-10-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0004_alter_asociado_responsable_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='obra_social',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
