# Generated by Django 3.2.15 on 2022-10-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0005_alter_asociado_obra_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='obra_social',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
