# Generated by Django 3.2.15 on 2022-10-15 18:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0006_alter_asociado_obra_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='requisitos',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
