# Generated by Django 3.2.15 on 2022-10-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0010_alter_asociadopagos_opcionelegida'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenadoreskempe',
            name='nacionalidad',
            field=models.CharField(default='Argentina', max_length=12),
        ),
    ]
