# Generated by Django 4.0.6 on 2023-03-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0012_alter_asociado_con_entrenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociadopagos',
            name='comentario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Comentarios'),
        ),
    ]
