# Generated by Django 4.0.6 on 2023-03-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0013_asociadopagos_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asociadoformaspago',
            options={'ordering': ['formaPago']},
        ),
    ]
