# Generated by Django 4.0.6 on 2023-03-28 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socio', '0014_alter_asociadoformaspago_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='tipoAsociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.asociadotipo', verbose_name='Tipo asociado'),
        ),
        migrations.AlterField(
            model_name='asociadopagos',
            name='comprobPago',
            field=models.ImageField(default='comprobante de Pago', null=True, upload_to='media/pagos', verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='asociadopagos',
            name='fechaPago',
            field=models.DateField(verbose_name='Fecha pago'),
        ),
        migrations.AlterField(
            model_name='asociadopagos',
            name='formaPago',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Forma pago'),
        ),
        migrations.AlterField(
            model_name='asociadopagos',
            name='montoAbonado',
            field=models.IntegerField(null=True, verbose_name='Monto Abonado'),
        ),
        migrations.AlterField(
            model_name='asociadopagos',
            name='montoDebeAbonar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monto debe abonar:'),
        ),
        migrations.AlterField(
            model_name='asociadopagos',
            name='opcionElegida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socio.asociadocosto', verbose_name='Forma:'),
        ),
        migrations.AlterField(
            model_name='asociadopagos',
            name='personaAsociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Persona Asociada'),
        ),
        migrations.AlterField(
            model_name='asociadopagos',
            name='tipoAsociadoPago',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo:'),
        ),
    ]
