# Generated by Django 4.0.6 on 2023-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0015_alter_asociado_tipoasociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenadoreskempe',
            name='seguro',
            field=models.BooleanField(default=False),
        ),
    ]
