# Generated by Django 4.0.6 on 2023-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0016_entrenadoreskempe_seguro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociado',
            name='vigente',
        ),
        migrations.AddField(
            model_name='asociado',
            name='asiste',
            field=models.BooleanField(default=False),
        ),
    ]
