# Generated by Django 4.0.6 on 2023-05-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0019_remove_entrenadoreskempe_desde_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
