# Generated by Django 4.0.6 on 2023-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0020_alter_asociado_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociado',
            name='numero_emmac',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='numero Emmac'),
        ),
    ]
