# Generated by Django 4.0.6 on 2023-09-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0027_alter_asociado_fecha_emision_emmac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asociado',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
