# Generated by Django 3.2.15 on 2022-10-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_persona_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(max_length=40),
        ),
    ]
