# Generated by Django 3.2.15 on 2022-10-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20221014_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ciudad',
            field=models.CharField(max_length=60),
        ),
    ]
