# Generated by Django 3.2.15 on 2022-10-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_persona_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.CharField(max_length=80),
        ),
    ]
