# Generated by Django 4.0.6 on 2022-11-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_persona_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fotoDni',
            field=models.ImageField(upload_to='media/fotoDni'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fotoPerfil',
            field=models.ImageField(upload_to='media/fotoPerfil'),
        ),
    ]
