# Generated by Django 4.0.6 on 2023-02-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_persona_fotodni_alter_persona_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(help_text='sin guiones', max_length=11, primary_key=True, serialize=False, verbose_name='cuil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
