# Generated by Django 4.0.6 on 2023-03-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_persona_cuil_alter_persona_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fotoDni',
            field=models.ImageField(default='foto Dni', upload_to='media/fotoDni'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fotoPerfil',
            field=models.ImageField(default='foto Perfil', upload_to='media/fotoPerfil'),
        ),
    ]
