# Generated by Django 4.0.6 on 2023-03-08 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_persona_fotodni_alter_persona_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cuil',
            field=models.CharField(help_text='sin guiones', max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='cuil'),
        ),
    ]
