"""
Django settings for triaCba project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"  # esto lo agregue para que funcione. SACAR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8#-bio!0qwi6+69ku8d4&w4i!slot$70ao-m-3hj#@agm_0^4f'
#SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '8#-bio!0qwi6+69ku8d4&w4i!slot$70ao-m-3hj#@agm_0^4f')


#SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG_PROPAGATE_EXCEPTIONS = True


# security.W018
#DEBUG = True

# security.W016
CSRF_COOKIE_SECURE = False

# security.W012
SESSION_COOKIE_SECURE = False

# security.W008
SECURE_SSL_REDIRECT = False

# security.W004
#SECURE_HSTS_SECONDS = 31536000  # One year in seconds

# Another security settings
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#SECURE_HSTS_PRELOAD = True
#SECURE_CONTENT_TYPE_NOSNIFF = True

#SILENCED_SYSTEM_CHECKS = ["models.W001"]


#ALLOWED_HOSTS = ['127.0.0.1']
ALLOWED_HOSTS = ['127.0.0.1' ]

# Application definition

INSTALLED_APPS = [
    
    'admin_interface',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps',
    'apps.escuela',
    'apps.registro',
    'apps.socio',
    'apps.inscripcion',
    'apps.usuarios',
    'apps.entrenadores',
    'apps.emails',
    'crispy_forms',
    'import_export',
    'ckeditor',
    'ckeditor_uploader',
    
    
    
   
    
    ]


CKEDITOR_UPLOAD_PATH = "uploads/"


CRISPY_TEMPLATE_PACK = 'bootstrap4'
X_FRAME_OPTIONS ='SAMEORIGIN'
#X_FRAME_OPTIONS = 'DENY'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'triaCba.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'DIRS': ['./templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'triaCba.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'triaCba.db',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'triaCba',
        'USER': 'postgres',
        'PASSWORD': '135795',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
#STATIC_URL = 'static/'
MEDIA_URL = '/media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.Persona'

LOGIN_REDIRECT_URL = reverse_lazy('index')
LOGOUT_REDIRECT_URL = reverse_lazy('login')




EMAIL__BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_PORT = 587
EMAIL_HOST_USER = 'tesoreriatriatloncba@gmail.com'
EMAIL__HOST_PASSWORD = 'keiewfqobsfjxhzh'

# EMAIL__BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'c1940284.ferozo.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 465
# EMAIL_HOST_USER = 'automatico@triatloncordoba.org'
# EMAIL__HOST_PASSWORD = 'vivalaT2022'


IMPORT_EXPORT_USE_TRANSACTIONS = True

import socket
s = socket.socket()
address = '127.0.0.1'  # or 192.168.0.47
port = 4001  # port number is a number, not string
try:
    s.connect((address, port))
    # originally, it was
    # except Exception, e:
    # but this syntax is not supported anymore.
except Exception as e:
    print("something's wrong with %s:%d. Exception is %s" % (address, port, e))
finally:
    s.close()
