# Generated by Django 4.0.6 on 2023-10-29 20:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('email', models.CharField(max_length=250, verbose_name='TO (email)')),
                ('bcc', models.CharField(max_length=250, verbose_name='BCC')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=10)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
