# Generated by Django 4.0.6 on 2023-03-28 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EscuelaFormasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPago', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EscuelaPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.CharField(blank=True, max_length=40,
                 null=True, verbose_name='Tipo Asociado :')),
                ('formaPago', models.CharField(blank=True,
                 max_length=40, null=True, verbose_name='Forma pago')),
                ('montoDebeAbonar', models.IntegerField(
                    blank=True, null=True, verbose_name='Monto a abonar:')),
                ('montoAbonado', models.IntegerField(
                    null=True, verbose_name='Monto Abonado:')),
                ('comentario', models.CharField(blank=True,
                 max_length=150, null=True, verbose_name='Comentarios')),
                ('fechaPago', models.DateField(verbose_name='Fecha pago')),
                ('comprobPago', models.ImageField(default='comprobante de Pago',
                 null=True, upload_to='media/pagos', verbose_name='Comprobante de pago')),
                ('confirm_pago', models.BooleanField(default=False)),
                ('asociado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 to='socio.asociado', verbose_name='Persona Asociada')),
                ('opcionElegida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                 to='escuela.escuelacosto', verbose_name='Opcion Elegida')),
            ],
            options={
                'ordering': ['fechaPago'],
            },
        ),
        migrations.AddField(
            model_name='escuelacosto',
            name='formaPago',
            field=models.ForeignKey(
                default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='escuela.escuelaformaspago'),
        ),
        migrations.CreateModel(
            name='EscuelaEntrenadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('nacionalidad', models.CharField(
                    default='Argentina', max_length=12)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('observacion', models.CharField(
                    blank=True, max_length=50, null=True)),
                ('habilitado', models.BooleanField(default=False)),
                
            ],
        ),
        migrations.CreateModel(
            name='EscuelaTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=8)),
                ('cupo_turno', models.IntegerField()),
                ('desde', models.TimeField()),
                ('hasta', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EscuelaAsignacTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 to='escuela.escuelaentrenadores', verbose_name='Entrenador')),
                ('turno', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='escuela.escuelaturnos')),
            ],
        ),
    ]
