# Generated by Django 4.0.6 on 2023-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuelapagos',
            name='comprobPago',
            field=models.ImageField(default='comprobante de Pago', upload_to='media/pagos', verbose_name='Comprobante de pago'),
        ),
    ]
