# Generated by Django 4.0.6 on 2023-03-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_alter_escuelapagos_comprobpago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EscuelaAsignacTurno',
        ),
        migrations.DeleteModel(
            name='EscuelaEntrenadores',
        ),
        migrations.DeleteModel(
            name='EscuelaTurnos',
        ),
    ]
