# Generated by Django 4.0.6 on 2023-03-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_escuelaentrenadores_escuelafuncionesprofes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escuelafuncionesprofes',
            old_name='descricpcion',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='escuelafuncionesprofes',
            name='desde',
        ),
        migrations.RemoveField(
            model_name='escuelafuncionesprofes',
            name='hasta',
        ),
    ]
