# Generated by Django 4.0.6 on 2023-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_rename_descricpcion_escuelafuncionesprofes_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuelafuncionesprofes',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
