# Generated by Django 4.0.6 on 2023-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_alter_escuelafuncionesprofes_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuelaasignacturno',
            name='hs_semanal',
            field=models.IntegerField(default=0, verbose_name='Hs semanales'),
        ),
        migrations.AlterField(
            model_name='escuelafuncionesprofes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
