# Generated by Django 4.0.6 on 2023-03-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0007_escuelaasignacturno_hs_semanal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuelafuncionesprofes',
            name='funcion',
            field=models.CharField(max_length=20),
        ),
    ]
