# Generated by Django 4.0.6 on 2023-03-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0016_entrenadoreskempe_seguro'),
        ('escuela', '0008_alter_escuelafuncionesprofes_funcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscuelaAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('asistencia', models.BooleanField(verbose_name='Asistencia')),
                ('asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socio.asociado', verbose_name='Asociado')),
            ],
        ),
    ]
