# Generated by Django 4.0.6 on 2023-04-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0010_escuelaasistencia_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuelapagos',
            name='tipoPago',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Entrenador :'),
        ),
    ]
